title: Yasmin Hilliam, PhD
logo: assets/img/IMG_3613.jpg
description: Postdoctoral associate @ University of Pittsburgh<br>< href="http://www.mmg.pitt.edu/lab/bomberger-lab">Bomberger lab</a> | <a href="http://www.mmg.pitt.edu/lab/cooper-lab">Cooper lab</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
